#+title: Mantra
#+last_update: 2023-01-25 23:21:27
#+tags: tips
#+description: 주문을 외워봐
#+layouge: page

* Mantra
 #+begin_quote
 Plans are useless, but planning is indispensable. - General Dwight D. Eisenhower
 #+end_quote

 #+begin_quote
 Enthusiasm is common. Endurance is rare. - Angela Duckworth
 #+end_quote

#+begin_quote
Speech is silver, silence is golden. - Thomas Carlyle
#+end_quote

#+begin_quote
We don't rise to the level of our expectations; we fall to the level of our
training. - Archilochos
#+end_quote

#+begin_quote
Young man, in mathematics you don't understand things. You just get used to
them. - John von Neumann
#+end_quote

** An Old Hacker's Tips

 I stole this from [[https://madned.substack.com/p/an-old-hackers-tips-on-staying-employed][here]].


*** The "Do It Anyway" Principle

#+begin_quote
... but sooner or later you will end up on some task or project that is
difficult to accomplish and/or generally unpleasant, all due to factors outside
of your control.
#+end_quote

#+begin_quote
.. would be the people that somehow got their tasks done anyway, even though
there were ridiculous contstraints imposed by our environment issues that made it
a lot harder.
#+end_quote

#+begin_quote
The brutal truth though is, ... We are all constantly measured in the eyes of
our employers by what we actually deliver, and those who can find a way to
succeed even in the face of adversity will always have an advantage over those
who cannot, or do not want to.
#+end_quote

*** The "Two-and-Done" Rule

#+begin_quote
It has to do with how to handle disagreements that come up at work.... have a
pretty strong desire to always have the right answer to things, ... I would
tenaciously argue my point, without letting go.
#+end_quote

#+begin_quote
... I would let them know just why they were *wrong*, and why we needed to do it
*my way* ... because something that I knew was better was being ignored.
#+end_quote

#+begin_quote
But this take-no-prisoners approach to debate **did not** do me any good... it
would negatively impact my ability to affect change. If I did this too often,
people would begin to see me as argumentative, difficult to work with, not a
team player, ....
#+end_quote

#+begin_quote
.... I'm still a big fan of being right all the time, ... What's changed over
the years though is first, an enhanced understanding that I in fact **am not
right all the time**. But also that even when I am right, it isn't always a
guarantee that others will **follow my advice**, and if they do not, that it's
sill *OK*.
#+end_quote


#+begin_quote
... I will state my case *the first time*, and if whoever is arguing to the
contrary does not agree after hearing my position, I'll *let it go*. But the next
time the opportunity comes up, I will argue my point *again*. Maybe allowing for a
gap of time for people to consider my original point, or maybe allowing me time
to refine and rephrase my ideas to be more convincing.
#+end_quote

#+begin_quote
... I will state my case *the first time*, and if whoever is arguing to the
contrary does not agree after hearing my position, I'll *let it go*. But the next
time the opportunity comes up, I will argue my point *again*. Maybe allowing for a
gap of time for people to consider my original point, or maybe allowing me time
to refine and rephrase my ideas to be more convincing.If I fail to ... the
second time though, **I am done.** .... "OK, let's go your way then. I still don't
completely agree with everything proposed here, but I think I've made my case,
and we ened to **move on**."
#+end_quote

#+begin_quote
Yielding in an argument like this has some weird, powerful effects. One is it
kind of releases you from responsibility if things should go wrong. And if a
truly bad decision has been made, it is actually pretty likely that things *wil*
start going wrong. If you fail to convince people after two tries, you really do
have to get behind the decision, and not try to sabotage or undermine it.
#+end_quote

#+begin_quote
... it bumps up your personal brand, as someone who should maybe be listened to
more often.
#+end_quote
